version: '2.1'

services:
  node:
    container_name: io.evix
    image: ghcr.io/wouterds/evix.io
    restart: unless-stopped
    mem_limit: 128mb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ioevix-http.rule=Host(`evix.io`)"
      - "traefik.http.routers.ioevix-http.entrypoints=web"
    networks:
      - reverse-proxy
    env_file:
      - .env

networks:
  reverse-proxy:
    external: true
