name: 'code-review'
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependencies
      run: make node_modules
    - name: Linting
      run: make lint
