name: release

on:
  push:
    tags: ['v*.*.*']

jobs:
  code-review:
    uses: ./.github/workflows/code-review.yml

  build:
    runs-on: ubuntu-latest
    needs: code-review
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: zip -r build.zip ./public
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.cf-pages.outputs.url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./
      - run: unzip build.zip
      - uses: cloudflare/pages-action@v1
        id: cf-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: evix-io
          directory: ./public
